CREATE TABLE USERS(
    USERID NUMERIC(11),
    TOTEXPERIMENTS NUMERIC(11),
    AVGEXPAMOUNT FLOAT(5,2),
    COMMONCOMPOUND NUMERIC(11),
    PRIMARY KEY(USERID)
);
CREATE TABLE US_CMP(
    USERID NUMERIC(11),
    COMPOUNDID NUMERIC(11),
    FREQUENCY NUMERIC(11),
    PRIMARY KEY(USERID,COMPOUNDID),
    FOREIGN KEY (USERID) REFERENCES USERS
);